# Generated by Django 3.2.21 on 2023-11-24 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20231123_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='readBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
